version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: travel_companion
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8001:8000"
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgresql+asyncpg://myuser:mypassword@db:5432/travel_companion
      - SECRET_KEY=my-super-secret-jwt-key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db

volumes:
  postgres_data:
