"""add itinerary fields to trip

Revision ID: 8367046ae9a1
Revises: 9d3f503f79f1
Create Date: 2026-09-25 17:51:39.829950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8367046ae9a1'
down_revision: Union[str, Sequence[str], None] = '9d3f503f79f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('itinerary_json', sa.JSON(), nullable=True))
    op.add_column('trips', sa.Column('is_generated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'is_generated')
    op.drop_column('trips', 'itinerary_json')
    # ### end Alembic commands ###
